markdown:       kramdown
kramdown:
  auto_ids:     true
encoding:       UTF-8
exclude:
  - .git/
  - package.json
  - package-lock.json
  - node_modules
sass:
  sass_dir: ./
  style: compressed

theme: cayman

# remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

title: ":closed_lock_with_key: pswd"
description: "a flexible way to generate secure password"

twitter:
  username: ajr_almeidan

author:
  name: A Junior
  twitter: iamajr
